# Introdução à Programação para Ciência de Dados

### Aula 15: Numpy

**Professor:** Igor Malheiros

## Numpy

Numpy, (*Numeric Python*) é a principal biblioteca de Python para computação científica. Ela oferece diversas ferramentas de alta performance para serem trabalhados em Arrays e Matrizes.

O Numpy possui ferramentas para se trabalhar com álgebra linear, ciência de dados, cálculo numérico, etc.

Além de fornecer uma vasta opção de ferramentas, uma operação utilizando Numpy pode ser até 50 vezes mais rápida do que a mesma operação utilizando `list` em Python. Isso se deve pela forma como o Numpy é implementado, os dados são sempre alocados de forma contígua na memória do computador. Além disso, o Numpy é foi feito em cima da linguagem **C** que é mais eficiente do que Python.

Em um primeiro momento pode ser questionado o motivo de querermos utilizar algo diferente, mas que pode realizar a mesma tarefa. Se não tivermos muita atenção quanto ao tempo que usamos para resolver um problema, nosso programa pode passar horas ou até anos em execução até encontrar uma resposta. Isso acontece principalmente quando estamos trabalhando com operações complexas (como operações em matrizes) ou com um grande volume de dados (comuns em ciência de dados). Assim, o uso de ferramentas mais eficientes são necessárias para resolvermos os problemas em um tempo útil.

### Criando arrays numpy

O numpy fornece diversas formas para criarmos arrays e matrizes, utilizando alguns padrões ou não. Estudaremos algumas delas.

- A primeira que vamos aprender é utilizando uma *lista* de Python.

</br>

```Python
import numpy as np

# Criando array de uma lista diretamente
npl = np.array([1,2,3,4,5])

# Criando array 2D por uma lista de listas diretamente
npm = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

- Outra forma é utilizar a função `arange(start, stop, step)` passando um valor inicial `start` um valor final `stop` e o intervalo entre os valores `step`.

```Python
import numpy as np

# Criando array em um intervalo np.arange(start, stop, step)
nparange = np.arange(10, 21, 2)
# array([10, 12, 14, 16, 18, 20])
```

</br>

- Podemos também utilizar a função `linspace(start, end, num)` que cria um array numpy com `num` elementos começando em `start` e terminando em `end`, o intervalo entre os elementos é sempre constante.

</br>

```Python
import numpy as np

# Criando um array igualmente espaçado np.linspace(start, end, num)
nplin = np.linspace(10, 100, 10)
# array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])
```

</br>

- Uma forma simples para criarmos uma lista de tamanho `n` com valores aleatórios é utilizando a função `random.rand(n)`, os valores aleatórios serão entre $0$ e $1$. Se quisermos criar um array multi-dimensional com `random.rand()`, basta acrescentarmos mais dimensões na chamada da função. Para valores inteiros, podemos utilizar a função `random.randint(menor, maior, n)`, onde o array criado possui valores inteiros aleatórios entre `menor` e `maior`, o tamanho do array é `n`. Se quisermos criar um array multi-dimensional com `random.randint()`, em vez de `n`, passaremos uma tupla `(dim1, dim2)` para indicar as dimensões da matriz.

</br>

```Python
import numpy as np

# Criando um array 1D com valores aleatórios np.random.rand(n)
rand_1 = np.random.rand(5)
# array([0.6592339 , 0.81193336, 0.51086174, 0.68363204])

# Criando um array 2D com valores aleatórios np.random.rand(dim1, dim2)
rand_2 = np.random.rand(2, 3)
# array([[0.67427651, 0.30781065, 0.70036505],
#        [0.06415093, 0.22410801, 0.85031702]])

# Criando um array 1D com valores aleatórios np.random.randint(menor, maior, n)
randint_1 = np.random.randint(1, 10, 8)
# array([1, 4, 1, 4, 8, 1, 6, 2])

# Criando um array 2D com valores aleatórios np.random.randint(menor, maior, (dim1, dim2))
randint_2 = np.random.randint(1, 10, (2, 3))
# array([[4, 9, 8],
#        [9, 3, 6]])
```

</br>

- Outro tipo de array/matriz muito comum é quando precisamos de um array com valores zerados ou iguais à $1$. Para isso, podemos utilizar as funções `zeros(n)`/`zeros((dim1, dim2))` e `ones(n)`/`ones((dim1, dim2)`, onde passaremos a quantidade de elementos/dimensões do array que queremos criar.

</br>

```Python
# Criando array 1D com valores 0 np.zeros(n)
npzeros_1 = np.zeros(7)
# array([0., 0., 0., 0., 0., 0., 0.])

# Criando array 2D com valores 0 np.zeros((dim1, dim2))
npzeros_2 = np.zeros((4, 2))
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.],
#        [0., 0.]])


# Criando array 1D com valores 1 np.ones(n)
npones_1 = np.ones(7)
# array([1., 1., 1., 1., 1., 1., 1.])

# Criando array 2D com valores 1 np.ones((dim1, dim2))
npones_2 = np.ones((4, 2))
# array([[1., 1.],
#        [1., 1.],
#        [1., 1.],
#        [1., 1.]])
```

</br>

- Caso seja necessário criar um array/matriz com o mesmo valor que seja diferente de $0$ ou $1$, podemos utilizar a função `full(n, valor)`/`full((dim1, dim2), valor)` para criarmos um array/matriz de `n`/`(dim1,dim2)` com valores iguais a `valor`.

</br>

```Python
# Criando array 1D com valores v np.full(5, 12)
npdoze_1 = np.full(5, 12)
# array([12, 12, 12, 12, 12])

# Criando array 2D com valores v np.full((2, 2), 12)
npdoze_2 = np.full((2, 2), 12)
# array([[12, 12],
#        [12, 12]])
```

</br>

- Por último, podemos criar uma matriz identidade com a função `eye(n)`, passando a dimensão da matriz pelo valor `n`.

</br>

```Python
# Criando matriz identidade np.eye(n)
ident = np.eye(5)
# array([[1., 0., 0., 0., 0.],
#        [0., 1., 0., 0., 0.],
#        [0., 0., 1., 0., 0.],
#        [0., 0., 0., 1., 0.],
#        [0., 0., 0., 0., 1.]])
```

In [36]:
# Criando array de uma lista diretamente
l = [1, 2, 3, 4, 5]
npa = np.array(l)
npa

array([1, 2, 3, 4, 5])

In [38]:
# Criando array 2D por uma lista de listas diretamente
npm = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
npm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Criando array em um intervalo np.arange(start, stop, step)

nparange = np.arange(0, 10, 3)
nparange

array([0, 3, 6, 9])

In [44]:
# Criando um array igualmente espaçado np.linspace(start, end, num)
nplinspace = np.linspace(10, 100, 11)
nplinspace

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [45]:
# Criando um array 1D com valores aleatórios np.random.rand(n)
nparand = np.random.rand(5)
nparand

array([0.90406245, 0.98977145, 0.67633142, 0.75975777, 0.48902466])

In [46]:
# Criando um array 2D com valores aleatórios np.random.rand(dim1, dim2)
npmrand = np.random.rand(2, 3)
npmrand

array([[0.30241781, 0.96049331, 0.7757788 ],
       [0.45865407, 0.13238635, 0.20988818]])

In [47]:
# Criando um array 1D com valores aleatórios np.random.randint(menor, maior, n)
nparandint = np.random.randint(0, 20, 5)
nparandint

array([ 8, 14,  2, 11, 11])

In [48]:
# Criando um array 2D com valores aleatórios np.random.randint(menor, maior, (dim1, dim2))
npmrandint = np.random.randint(0, 20, (4, 3))
npmrandint

array([[ 0, 19,  0],
       [17, 19, 13],
       [16,  6, 15],
       [18,  8, 19]])

In [49]:
# Criando array 1D com valores 0 np.zeros(n)
npazeros = np.zeros(7)
npazeros

array([0., 0., 0., 0., 0., 0., 0.])

In [50]:
# Criando array 2D com valores 0 np.zeros((dim1, dim2))
npmzeros = np.zeros((2, 3))
npmzeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# Criando array 1D com valores 1 np.ones(n)
npaones = np.ones(6)
npaones

array([1., 1., 1., 1., 1., 1.])

In [52]:
# Criando array 2D com valores 1 np.ones((dim1, dim2))
npmones = np.ones((4, 4))
npmones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
# Criando array 1D com valores v np.full(5, 12)
npafull = np.full(5, 14)
npafull

array([14, 14, 14, 14, 14])

In [54]:
# Criando array 2D com valores v np.full((2, 2), 12)
npmfull = np.full((2, 2), 12)
npmfull

array([[12, 12],
       [12, 12]])

In [55]:
# Criando matriz identidade np.eye(n)
ident = np.eye(5)
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Dimensões e Forma

Podemos identificar a quantidade de dimensões de um array numpy acessamos o campo `ndim` e para a forma do array acessamos o campo `shape.

```Python
npones_2 = np.ones((4, 2))

print(npones_2.ndim)   # 2
print(npones_2.shape)  # (4, 2)
```

In [58]:
# Acessando dimensões e forma
npones = np.ones((4, 3))

print(npones.shape)

(4, 3)


### Acessando elementos

Os acessos aos elementos ou às linhas/colunas de um array numpy funciona de forma similar ao que já conhecemos em listas. A principal diferença é que para matrizes, separaremos os índices de acesso às dimensões por uma vírgula, em vez de abrir novos `[]`.

</br>

```Python
npl = np.array([1, 2, 3, 4, 5])

print(npl[0])  # 1
print(npl[2])  # 3
print(npl[-1]) # 5

npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

print(npm[0, 0])   # 1
print(npm[2, 1])   # 12
print(npm[-1, -1]) # 15
```

</br>

Similar às listas, é possível fazer acessos via *slices* nos arrays e matrizes numpy.

</br>

```Python
npl = np.array([1, 2, 3, 4, 5])

print(npl[2:4])  # [3, 4]
print(npl[:2])   # [1, 2] 
print(npl[2:])   # [3, 4, 5] 

npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

print(npm[0:2, 2:4])   # [[3, 4], [8, 9]]
print(npm[:2, :2])     # [[1, 2], [6, 7]]
```

In [61]:
# Acessando elementos array 1D
npl = np.array([1, 2, 3, 4, 5])

npl[2]

3

In [64]:
# Acessando elementos array 2D
npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

npm[-1, -1]

15

In [66]:
# Acessando slices 1D
npa[2:4]

array([3, 4])

In [67]:
# Acessando slices 2D
npm[:2, :2]

array([[1, 2],
       [6, 7]])

### Modificando elementos

Os arrays de numpy são mutáveis, ou seja, podemos modificar seus elementos. Além de alterarmos elemento por elemento como já estamos acostumados, podemos fazer alterações de slices de uma só vez, ou seja, podemos modificar linhas, colunas ou submatrizes inteiras de uma só vez.

</br>

```Python
npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

npm[2, 1] = 100
# array([[  1,   2,   3,   4,   5],
#        [  6,   7,   8,   9,  10],
#        [ 11, 100,  13,  14,  15]])

npm[0, :] = 0
# array([[  0,   0,   0,   0,   0],
#        [  6,   7,   8,   9,  10],
#        [ 11, 100,  13,  14,  15]])

npm[:, 4] = 2
# array([[  0,   0,   0,   0,   2],
#        [  6,   7,   8,   9,   2],
#        [ 11, 100,  13,  14,   2]])
```

In [68]:
# Modificando um elemento
npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

npm[2, 1] = 1000
npm

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11, 1000,   13,   14,   15]])

In [69]:
# Modificando uma linha
npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])

npm[0, :] = 0
npm

array([[ 0,  0,  0,  0,  0],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [70]:
# Modificando uma coluna
npm = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])
npm[:, 1] = 5
npm

array([[ 1,  5,  3,  4,  5],
       [ 6,  5,  8,  9, 10],
       [11,  5, 13, 14, 15]])

## Exercício 1

Construa uma matriz numpy com `10x10` com valores `1`, mas a borda desse array deve ter valores `0`.

In [77]:
matriz = np.ones((10, 10))
matriz[0, :] = 0
matriz[:, 0] = 0
matriz[-1,:] = 0
matriz[:, -1] = 0
# matriz

l = [1, 2, 3, 4, 5]
l[len(l) - 1]

5