# Introdução à Programação para Ciência de Dados

### Aula 16: Numpy II

**Professor:** Igor Malheiros

## Operações aritméticas com array e escalar

As operações entre um array (ou matriz) Numpy e um escalar são feitas elemento por elemento.

### Arrays


\begin{equation}
AX = [x_{1}, x_{2}, x_{3}]
\end{equation}

\begin{equation}
escalar = e
\end{equation}

- Soma

\begin{equation}
AX + e = [x_{1} + e, x_{2} + e, x_{3} + e]
\end{equation}

- Subtração

\begin{equation}
AX - e = [x_{1} - e, x_{2} - e, x_{3} - e]
\end{equation}

- Multiplicação

\begin{equation}
AX * e = [x_{1} * e, x_{2} * e, x_{3} * e]
\end{equation}

- Divisão

\begin{equation}
AX / e = [x_{1} / e, x_{2} / e, x_{3} / e]
\end{equation}

</br></br>

```Python
AX = np.array([1,2,3])
e = 3

AX + e # array([4, 5, 6])
AX - e # array([-2, -1,  0])
AX * e # array([3, 6, 9])
AX / e # array([0.33333333, 0.66666667, 1.])
```

</br></br>

### Matrizes

\begin{equation}
MX =
\begin{bmatrix}
    x_{11}   &  x_{12} \\
    x_{21}   &  x_{22} \\
    x_{31}   &  x_{32} \\
\end{bmatrix}
\end{equation}

- Soma

\begin{equation}
MX + e =
\begin{bmatrix}
    x_{11} + e   &  x_{12} + e \\
    x_{21} + e   &  x_{22} + e \\
    x_{31} + e   &  x_{32} + e \\
\end{bmatrix}
\end{equation}

- Subtração

\begin{equation}
MX - e =
\begin{bmatrix}
    x_{11} - e   &  x_{12} - e \\
    x_{21} - e   &  x_{22} - e \\
    x_{31} - e   &  x_{32} - e \\
\end{bmatrix}
\end{equation}

- Multiplicação

\begin{equation}
MX * e =
\begin{bmatrix}
    x_{11} * e   &  x_{12} * e \\
    x_{21} * e   &  x_{22} * e \\
    x_{31} * e   &  x_{32} * e \\
\end{bmatrix}
\end{equation}

- Divisão

\begin{equation}
MX / e =
\begin{bmatrix}
    x_{11} / e   &  x_{12} / e \\
    x_{21} / e   &  x_{22} / e \\
    x_{31} / e   &  x_{32} / e \\
\end{bmatrix}
\end{equation}

</br></br>

```Python
MX = np.array(
[[1, 2, 3],
 [6, 5, 4],
 [7, 8, 9]]
)

e = 3

MX + e
# array([[ 4,  5,  6],
#        [ 9,  8,  7],
#        [10, 11, 12]])

MX - e
# array([[-2, -1,  0],
#        [ 3,  2,  1],
#        [ 4,  5,  6]])

MX * e
# array([[ 3,  6,  9],
#        [18, 15, 12],
#        [21, 24, 27]])

MX / e
# array([[0.33333333, 0.66666667, 1.        ],
#        [2.        , 1.66666667, 1.33333333],
#        [2.33333333, 2.66666667, 3.        ]])
```

</br></br>

In [1]:
import numpy as np

AX = np.array([1,2,3])
MX = np.array(
[[1, 2, 3],
 [6, 5, 4],
 [7, 8, 9]]
)
e = 3

In [5]:
# AX + e
AX + e

array([4, 5, 6])

In [6]:
# AX - e
AX - e

array([-2, -1,  0])

In [7]:
# AX * e
AX * e

array([3, 6, 9])

In [8]:
# AX / e
AX / e

array([0.33333333, 0.66666667, 1.        ])

In [9]:
# MX + e
MX + e

array([[ 4,  5,  6],
       [ 9,  8,  7],
       [10, 11, 12]])

In [10]:
# MX - e
MX - e

array([[-2, -1,  0],
       [ 3,  2,  1],
       [ 4,  5,  6]])

In [11]:
# MX * e
MX * e

array([[ 3,  6,  9],
       [18, 15, 12],
       [21, 24, 27]])

In [12]:
# MX / e
MX / e

array([[0.33333333, 0.66666667, 1.        ],
       [2.        , 1.66666667, 1.33333333],
       [2.33333333, 2.66666667, 3.        ]])

## Operações lógicas com array e escalar

As operações lógicas entre um array (ou matriz) Numpy e um escalar também são feitas elemento por elemento. Porém, o resultado para cada elemento é o resultado do operador lógico (`True` ou `False`) aplicado em cada elemento.

### Arrays

- Igualdade

\begin{equation}
AX = e = [x_{1} = e, x_{2} = e, x_{3} = e]
\end{equation}

- Diferença

\begin{equation}
AX \neq e = [x_{1} \neq e, x_{2} \neq e, x_{3} \neq e]
\end{equation}

- Menor (menor ou igual)

\begin{equation}
AX \leq e = [x_{1} \leq e, x_{2} \leq e, x_{3} \leq e]
\end{equation}

- Maior (maior ou igual)

\begin{equation}
AX \geq e = [x_{1} \geq e, x_{2} \geq e, x_{3} \geq e]
\end{equation}
</br></br>

```Python
AX = np.array([1,2,3])
e = 3

AX == e # array([False, False, True])
AX != e # array([True, True,  False])
AX < e  # array([True, True, False])
AX >= e # array([False, False, True])
```

</br></br>


### Matrizes

- Igualdade

\begin{equation}
MX = e =
\begin{bmatrix}
    x_{11} = e   &  x_{12} = e \\
    x_{21} = e   &  x_{22} = e \\
    x_{31} = e   &  x_{32} = e \\
\end{bmatrix}
\end{equation}

- Diferença

\begin{equation}
MX \neq e =
\begin{bmatrix}
    x_{11} \neq e   &  x_{12} \neq e \\
    x_{21} \neq e   &  x_{22} \neq e \\
    x_{31} \neq e   &  x_{32} \neq e \\
\end{bmatrix}
\end{equation}

- Menor (menor ou igual)

\begin{equation}
MX \leq e =
\begin{bmatrix}
    x_{11} \leq e   &  x_{12} \leq e \\
    x_{21} \leq e   &  x_{22} \leq e \\
    x_{31} \leq e   &  x_{32} \leq e \\
\end{bmatrix}
\end{equation}

- Maior (maior ou igual)

\begin{equation}
MX \geq e =
\begin{bmatrix}
    x_{11} \geq e   &  x_{12} \geq e \\
    x_{21} \geq e   &  x_{22} \geq e \\
    x_{31} \geq e   &  x_{32} \geq e \\
\end{bmatrix}
\end{equation}

</br></br>

```Python
MX == e
# array([[False, False,  True],
#        [False, False, False],
#        [False, False, False]])

MX != e
# array([[ True,  True, False],
#        [ True,  True,  True],
#        [ True,  True,  True]])

MX < e
# array([[ True,  True, False],
#        [False, False, False],
#        [False, False, False]])

MX >= e
# array([[False, False,  True],
#        [ True,  True,  True],
#        [ True,  True,  True]])
```

</br></br>

In [14]:
# AX == e
AX == e

array([False, False,  True])

In [15]:
# AX != e
AX != e

array([ True,  True, False])

In [16]:
# AX < e
AX < e

array([ True,  True, False])

In [17]:
# AX >= e
AX >= e

array([False, False,  True])

In [19]:
# MX == e
MX == e

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [20]:
# MX != e
MX != e

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
# MX < e
MX < e

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [22]:
# MX >= e
MX >= e

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Any e All

As funções `any()` e `all()` são muito úteis para checagens do tipo "existe algum elemento" ou "todos os elementos são" em arrays Numpy. A função `any()` checa se ao menos um elemento do array Numpy é `True`. Enquanto que a função `all()` checa se todos os elementos de um array Numpy é `True`

</br></br>

```Python
alltrue = np.array([True, True, True, True, True])
onetrue = np.array([False, False, True, False, False])
allfalse = np.array([False, False, False, False, False])
onefalse = np.array([True, True, False, True, True])

np.all(alltrue) # true
np.all(onetrue) # false
np.all(allfalse) # false
np.all(onefalse) # false

np.any(alltrue) # true
np.any(onetrue) # true
np.any(allfalse) # false
np.any(onefalse) # true

```

</br></br>

Essas funções podem ser muito úteis com as operações lógicas entre arrays Numpy e escalares.

## Filtros (Masks)

Uma operação poderosa nos arrays numpy é a filtragem de elementos. Podemos utilizar os operadores lógicos para filtrar os elementos de um array ou matriz numpy.


</br>

```Python
nparr = np.array([[ 0, 19,  0],
                  [17, 19, 13],
                  [16,  6, 15],
                  [18,  8, 19]])

nparr[nparr >= 10] # array([19, 17, 19, 13, 16, 15, 18, 19])
nparr[(nparr > 5) & (nparr <= 12)] # array([6,  8])
```

In [23]:
alltrue = np.array([True, True, True, True, True])
onetrue = np.array([False, False, True, False, False])
allfalse = np.array([False, False, False, False, False])
onefalse = np.array([True, True, False, True, True])

nparr = np.array([[ 0, 19,  0],
                  [17, 19, 13],
                  [16,  6, 15],
                  [18,  8, 19]])

In [28]:
# Funcao any()
np.any(onefalse)

True

In [31]:
# Funcao all()
np.all(alltrue)

True

In [34]:
# Filtro
nparr[nparr > 15]

array([19, 17, 19, 16, 18, 19])

In [37]:
# Filtrando por Intervalo
# nparr[(nparr > 5) and (nparr <= 16)] # não funciona!
nparr[(nparr > 5) & (nparr <= 16)] # não funciona!

array([13, 16,  6, 15,  8])

## Operações entre Arrays (Matrizes)

As operações em arrays ou matrizes Numpy são feitas elemento por elemento. Por isso, os `shapes` das duas matrizes ou o tamanho dos arrays devem ser os mesmos.

### Arrays

\begin{equation}
A = [x_{1}, x_{2}, x_{3}]
\end{equation}

\begin{equation}
B = [y_{1}, y_{2}, y_{3}]
\end{equation}

- Soma

\begin{equation}
A + B = [x_{1} + y_{1}, x_{2} + y_{2}, x_{3} + y_{3}]
\end{equation}

- Subtração

\begin{equation}
A - B = [x_{1} - y_{1}, x_{2} - y_{2}, x_{3} - y_{3}]
\end{equation}

- Multiplicação

\begin{equation}
AB = [x_{1}y_{1}, x_{2}y_{2}, x_{3}y_{3}]
\end{equation}

- Divisão

\begin{equation}
A / B = [x_{1} / y_{1}, x_{2} / y_{2}, x_{3} / y_{3}]
\end{equation}

- Igualdade

\begin{equation}
A = B = [x_{1} = y_{1}, x_{2} = y_{2}, x_{3} = y_{3}]
\end{equation}

</br></br>

```Python
A = np.array([1,2,3])
B = np.array([4,5,6])

A + B  # array([5, 7, 9])
A - B  # array([-3, -3, -3])
A * B  # array([ 4, 10, 18])
A / B  # array([0.25, 0.4 , 0.5 ])
A == B # array([False, False, False])
```

</br></br>

### Matrizes

\begin{equation}
MA =
\begin{bmatrix}
    x_{11}   &  x_{12} \\
    x_{21}   &  x_{22} \\
    x_{31}   &  x_{32} \\
\end{bmatrix}
\end{equation}


\begin{equation}
MB =
\begin{bmatrix}
    y_{11}   &  y_{12} \\
    y_{21}   &  y_{22} \\
    y_{31}   &  y_{32} \\
\end{bmatrix}
\end{equation}


- Soma

\begin{equation}
MA + MB =
\begin{bmatrix}
    x_{11} + y_{11}   &  x_{12} + y_{12} \\
    x_{21} + y_{21}   &  x_{22} + y_{22} \\
    x_{31} + y_{31}   &  x_{23} + y_{23} \\
\end{bmatrix}
\end{equation}

- Subtração

\begin{equation}
MA - MB =
\begin{bmatrix}
    x_{11} - y_{11}   &  x_{12} - y_{12} \\
    x_{21} - y_{21}   &  x_{22} - y_{22} \\
    x_{31} - y_{31}   &  x_{23} - y_{23} \\
\end{bmatrix}
\end{equation}

- Multiplicação

\begin{equation}
MA * MB =
\begin{bmatrix}
    x_{11} * y_{11}   &  x_{12} * y_{12} \\
    x_{21} * y_{21}   &  x_{22} * y_{22} \\
    x_{31} * y_{31}   &  x_{23} * y_{23} \\
\end{bmatrix}
\end{equation}

- Divisão

\begin{equation}
MA / MB =
\begin{bmatrix}
    x_{11} / y_{11}   &  x_{12} / y_{12} \\
    x_{21} / y_{21}   &  x_{22} / y_{22} \\
    x_{31} / y_{31}   &  x_{23} / y_{23} \\
\end{bmatrix}
\end{equation}

- Igualdade

\begin{equation}
MA = MB =
\begin{bmatrix}
    x_{11} = y_{11}   &  x_{12} = y_{12} \\
    x_{21} = y_{21}   &  x_{22} = y_{22} \\
    x_{31} = y_{31}   &  x_{23} = y_{23} \\
\end{bmatrix}
\end{equation}


</br></br>

```Python
MA = np.array(
[[11, 12, 13],
 [21, 22, 23],
 [31, 32, 33]])

MB = np.array(
[[41, 42, 43],
 [51, 52, 53],
 [61, 62, 63]])

MA + MB
# array([[52, 54, 56],
#        [72, 74, 76],
#        [92, 94, 96]])

MA - MB
# array([[-30, -30, -30],
#        [-30, -30, -30],
#        [-30, -30, -30]])

MA * MB
# array([[ 451,  504,  559],
#        [1071, 1144, 1219],
#        [1891, 1984, 2079]])

MA / MB
# array([[0.26829268, 0.28571429, 0.30232558],
#        [0.41176471, 0.42307692, 0.43396226],
#        [0.50819672, 0.51612903, 0.52380952]])

MA == MB
# array([[False, False, False],
#        [False, False, False],
#        [False, False, False]])
```

</br></br>

In [38]:
A = np.array([1,2,3])
B = np.array([4,5,6])

MA = np.array(
[[11, 12, 13],
 [21, 22, 23],
 [31, 32, 33]])

MB = np.array(
[[41, 42, 43],
 [51, 52, 53],
 [61, 62, 63]])

In [39]:
# A + B
A + B

array([5, 7, 9])

In [40]:
# A - B
A - B

array([-3, -3, -3])

In [41]:
# A * B
A * B

array([ 4, 10, 18])

In [42]:
# A / B
A / B

array([0.25, 0.4 , 0.5 ])

In [43]:
# A == B
A == B

array([False, False, False])

In [44]:
# MA + MB
MA + MB

array([[52, 54, 56],
       [72, 74, 76],
       [92, 94, 96]])

In [45]:
# MA - MB
MA - MB

array([[-30, -30, -30],
       [-30, -30, -30],
       [-30, -30, -30]])

In [46]:
# MA * MB
MA * MB

array([[ 451,  504,  559],
       [1071, 1144, 1219],
       [1891, 1984, 2079]])

In [47]:
# MA / MB
MA / MB

array([[0.26829268, 0.28571429, 0.30232558],
       [0.41176471, 0.42307692, 0.43396226],
       [0.50819672, 0.51612903, 0.52380952]])

In [48]:
# MA == MB
MA == MB

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Produto interno

### Arrays

\begin{equation}
A = [x_{1}, x_{2}, x_{3}]
\end{equation}

\begin{equation}
B = [y_{1}, y_{2}, y_{3}]
\end{equation}

\begin{equation}
A \cdot B =
\begin{bmatrix}
    x_{1}   &  x_{2} & x_3
\end{bmatrix}
\cdot
\begin{bmatrix}
    y_{1} \\
    y_{2} \\
    y_{3} \\
\end{bmatrix}
\end{equation}

\begin{equation}
A \cdot B = x_{1}y_{1} + x_{2}y_{2} + x_{3}y_{3}
\end{equation}

### Matrizes

Para realizar a operação de produto interno $MA \cdot MB$ é necessário uma compatibilidade entre as dimensões de $MA$ e $MB$. A compatibilidade é, se a matriz $MA$ tem dimensão $nXm$ para a operação de produto do interno a matriz $MB$ deve possuir dimensões $mXn$, $n$ e $m$ podem ter valores iguais (caso de matrizes quadradas).

\begin{equation}
MA =
\begin{bmatrix}
    x_{11}   &  x_{12}  \\
    x_{21}   &  x_{22}  \\
    x_{31}   &  x_{32}  \\
\end{bmatrix}
\end{equation}

\begin{equation}
MB =
\begin{bmatrix}
    y_{11}   &  y_{12} & y_{13} \\
    y_{21}   &  y_{22} & y_{23} \\
\end{bmatrix}
\end{equation}

\begin{equation}
MA \cdot MB =
\begin{bmatrix}
    (x_{11}y_{11} + x_{12}y_{21})   &  
    (x_{11}y_{12} + x_{12}y_{22})   &
    (x_{11}y_{13} + x_{12}y_{23})  \\
    (x_{21}y_{11} + x_{22}y_{21})   &  
    (x_{21}y_{12} + x_{22}y_{22})   &
    (x_{21}y_{13} + x_{22}y_{23})  \\
    (x_{31}y_{11} + x_{32}y_{21})   &  
    (x_{31}y_{12} + x_{32}y_{22})   &
    (x_{31}y_{13} + x_{32}y_{23})  \\
\end{bmatrix}
\end{equation}

</br> </br>

```Python

A @ B   # 32
MA @ MB
# array([[1856, 1892, 1928],
#        [3386, 3452, 3518],
#        [4916, 5012, 5108]])
```

</br> </br>


## Produto Vetorial

\begin{equation}
A = [x_{1}, x_{2}, x_{3}]
\end{equation}

\begin{equation}
B = [y_{1}, y_{2}, y_{3}]
\end{equation}

\begin{equation}
A \times B =
\begin{bmatrix}
    (x_{2}y_{3} - x_{3}y_{2})   &  
    (x_{3}y_{1} - x_{1}y_{3})   &
    (x_{1}y_{2} - x_{2}y_{1})   \\
\end{bmatrix}
\end{equation}

</br> </br>

```Python
np.cross(A, B) # array([-3,  6, -3])
```

In [50]:
# A @ B
A @ B

32

In [51]:
# MA @ MB
MA @ MB

array([[1856, 1892, 1928],
       [3386, 3452, 3518],
       [4916, 5012, 5108]])

In [52]:
# np.cross(A, B)
np.cross(A, B)

array([-3,  6, -3])

## Exercício 1

Construa dois arrays numpy com `25` valores aleatórios inteiros variando no intervalo `[1, 20]`. Em seguida, verifique se existe algum elemento igual e na mesma posição entre os dois arrays.

In [64]:
a = np.random.randint(1, 21, 25)
b = np.random.randint(1, 21, 25)
print(a)
print(b)

np.any(a == b)

[ 9  9 18 18  5  6 18 15  6  8  8  6 16  2 11  7  1 12  2 10  1 17  8  4
  6]
[ 9  1  2 18  6  9  4 19 12 12 18  3 15  9 20 20  8  1 14 10  2 12  4  5
 17]


True

## Exercício 2

Construa uma função que determina se dois vetores são **ortogonais**.

In [67]:
def eh_ortogonal(vetor_1, vetor_2):
    if (vetor_1 @ vetor_2) == 0.0:
        return True
    else:
        return False
    

    
print(eh_ortogonal(np.array([1, 0]), np.array([0, 1])))
print(eh_ortogonal(np.array([1, 5]), np.array([4, 1])))
print(eh_ortogonal(np.array([2, -2]), np.array([2, 2])))

True
False
True


## Exercício 3

A norma de um vetor é obtida por meio do cálculo do comprimento desse vetor. Sabendo que

\begin{equation}
A = [x_{1}, x_{2}, x_{3}]
\end{equation}

\begin{equation}
\lVert A \rVert = \sqrt{x_{1}^{2} +x_{2}^{2} + x_{3}^{2}}
\end{equation}

\begin{equation}
\lVert A \rVert = \sqrt{A \cdot A}
\end{equation}

Faça uma função que recebe um vetor e calcula sua **norma**.

In [81]:
def norma(vetor):
    return ((vetor @ vetor) ** (1/2))


print(norma(np.array([3, -4])))

5.0


In [54]:
# Determinante:

a = np.array([[50, 29], [30, 44]])
int(np.linalg.det(a))

1330